apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    name: tln-prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30100
  selector:
    app: tln-prometheus
