apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    name: notification-service
spec:
  ports:
    - port: 8772
      targetPort: 8772
  selector:
    name: notification-service
