kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by:
        - alertname
        - cluster
        - service
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: slack-notifications
      routes:
      - receiver: slack-notifications
        match:
          severity: warning
    receivers:
    - name: slack-notifications
      slack_configs:
      - channel: "#alerts"
        send_resolved: true
        api_url: "write your slack channel url"
        text: "{{ range .Alerts }} {{ .Annotations.summary }}\n{{ .Annotations.description }}\n{{ end }}"

