apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    name: discovery-service
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30001
  selector:
    name: discovery-service


