apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper
  template:
    metadata:
      name: zookeeper
      labels:
        name: zookeeper
    spec:
      containers:
        - image: confluentinc/cp-zookeeper:7.3.0
          name: zookeeper
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181


---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeper-service
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    name: zookeeper